version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws/aws-sdk-php
    versions:
    - 3.172.2
    - 3.172.4
    - 3.173.13
    - 3.173.18
    - 3.173.23
    - 3.173.28
    - 3.173.4
    - 3.173.8
    - 3.175.0
    - 3.176.2
    - 3.176.7
    - 3.178.1
    - 3.178.5
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.3
    - 2.18.4
    - 2.18.5
  - dependency-name: google/cloud-pubsub
    versions:
    - 1.30.0
    - 1.30.1
  - dependency-name: google/cloud-tasks
    versions:
    - 1.9.0
